#!/bin/sh

mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD -e \
  "CREATE DATABASE IF NOT EXISTS  ${DB_NAME} /*\!40100 DEFAULT CHARACTER SET utf8 */;";
mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD -e \
    "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USERNAME}';";
mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD -e "FLUSH PRIVILEGES;";

alembic upgrade head