"""change ltc length to 60

Revision ID: 3902a76cea9f
Revises: 402ae24d582e
Create Date: 2022-12-05 10:16:14.866934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3902a76cea9f'
down_revision = '402ae24d582e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_status', 'arrival_time_at_lunar_colony_ltc',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_status', 'arrival_time_at_lunar_colony_ltc',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
