"""change ltc datetime to string

Revision ID: 402ae24d582e
Revises: 588e48d25335
Create Date: 2022-12-05 10:07:23.007150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '402ae24d582e'
down_revision = '588e48d25335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_status', 'arrival_time_at_lunar_colony_ltc',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_request_status_arrival_time_at_lunar_colony_ltc'), 'request_status', ['arrival_time_at_lunar_colony_ltc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_arrival_time_at_lunar_colony_ltc'), table_name='request_status')
    op.alter_column('request_status', 'arrival_time_at_lunar_colony_ltc',
               existing_type=sa.String(length=30),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
