"""create request id schema

Revision ID: 588e48d25335
Revises: 
Create Date: 2022-10-30 10:24:09.662800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588e48d25335'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_status',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('departure_time_from_warehouse_utc', sa.DateTime(), nullable=True),
    sa.Column('arrival_time_at_earth_space_station_utc', sa.DateTime(), nullable=True),
    sa.Column('arrival_time_at_lunar_colony_utc', sa.DateTime(), nullable=True),
    sa.Column('arrival_time_at_lunar_colony_ltc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_status')
    # ### end Alembic commands ###
